### ISSUE TITLE
Better error messages for non-tangelo-service python files

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/tangelo#355]
If a python file contains neither ``run()`` nor any functions marked with ``@tangelo.restful``, the error raised has to do with key-not-found in searching for those functions.  Instead there should be a particular error message saying that the file is not a valid Tangelo service.

**Comment by ronichoudhury** [comment]
I think this was fixed some time ago.  Instead of ``KeyError`` Tangelo shows an error saying that "GET" is a disallowed method for the service (it usually says "GET" because that's the default method used for many requests:  all browser-based requests, for examples, along with JQuery ajax requests that don't specify the method explicitly).

The other option here is to check all of the service module's functions to see if any is named ``run()``, or if any of them have the ``@tangelo.restful`` decorator.  In this case, we could provide a more precise error message, something like "this is not a valid Tangelo service - did you remember to mark the restful functions with @tangelo.restful, or include a run() function?".  But it may be overkill.  @jeffbaumes what do you think?

**Comment by jeffbaumes** [comment]
What you suggest is a good "debug mode" of operation, though in production you probably don't want the web server "talking to" the end user as if they were a developer. So I'm fine with the special message if in debug mode, but am also ok with just always sending the GET error - after reading any docs they should already understand that they need a run() function.

**Comment by ronichoudhury** [comment]
Let's just leave it as is then.  I'm also ok with the GET error, since Tangelo's MO is to first look for a ``run()`` function, then treat the service as though it's restful.  Closing.
