### ISSUE TITLE
Explain how to make a copy of the examples in a user directory for danger-free editing

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/tangelo#368]
To encourage app developers to experiment and learn, we should give explicit instructions early in the documentation about how to take the bundled examples (in, e.g., ``/usr/share``) and copy them wholesale into the user's tangelo_html directory so they can tinker with no fear of messing with files installed by pip, etc.

Idea courtesy of @berkgeveci.

**Comment by jeffbaumes** [comment]
Also recreate the config file that goes with the examples.
