### ISSUE TITLE
Merge config file and plugin config file

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/tangelo#482]
As per [this discussion](https://github.com/Kitware/tangelo/pull/479#discussion_r23930838)

**Comment by ronichoudhury** [comment]
As part of this issue, I am planning to remove the dynamic nature of plugin loading/unloading - going with the idea that you set up a Tangelo instance with plugins as a single application, I think it's reasonable to say that once it's going, you can't dynamically activate new plugins or deactivate running ones.

The main advantage is simplicity of semantics - there's no need to define what "unloading" a plugin means anymore.  There is just one phase in the beginning when plugins are loaded.  If anything goes wrong, the administrator can kill Tangelo, fix things, and try again.

Along with that advantage will come a dramatic reduction in LOC devoted to dealing with the logic of dynamic plugins.

I think the simplicity can be bought for a the generality of the current approach, something that I don't believe is of great use to end users anyway.  In the longer run, it will reduce the amount of debugging weirdness that may come up from the more complex approach.

@jeffbaumes, please let me know if you have any objections.

**Comment by jeffbaumes** [comment]
+1 for dramatic reduction in LOC
