### ISSUE TITLE
Implement "tangelo --watch" functionality

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/tangelo#516]
@jeffbaumes, @manthey, and I decided that

- the "watch" functionality is useful enough to keep around,
- it should go into a (bundled) plugin that will install a custom importation behavior into the global import handler,
- the existing service autoreload behavior should be moved into the watch plugin, and
- Tangelo should learn a new command line switch ``--watch`` which will be a shorthand for loading the watch plugin, sparing the user from having to mention it in the list of plugins by name

Further, we decided that having to say ``tangelo.paths(".")`` is a bug (and I will open a new issue (#514) to deal with that, as it is related but orthogonal to the current effort).

The upshot of all this is that developers will be able to write code using standard Python idioms (no ``tangelo.paths()`` or ``tangelo.local_import()``).  They can get the auto-reload behavior by saying ``--watch`` while they are developing, and omitting the flag in production.  The exact same source code will now exhibit different behaviors, based on a choice at the very top level.

Personally, this assuages all my concerns about putting non-standard behavior in core, while still allowing access to it when it's needed.

@manthey will take the lead in moving the behaviors into a plugin, while I'll advise on matters like how to implement the command line option, etc.

Thanks for your thoughts everyone!

(See #513 for full, original discussion on this topic.)

**Comment by manthey** [comment]
Added in PR #528.
