### ISSUE TITLE
Allow changing cherrypy pool size

### ISSUE THREAD

**Issue by manthey** [Kitware/tangelo#532]
Perhaps expose cherrypy settings in a general way, too.

**Comment by ronichoudhury** [comment]
:+1:

One reason I've never committed to a general mechanism for manipulating CherryPy settings is that I've always viewed Tangelo as sort of its own API, merely implemented over CherryPy currently. We could either (1) admit that Tangelo is tied to CherryPy forever and then systematically expose every CherryPy setting through a Tangelo API, or (2) add a general ``setting()`` function to the API that takes a string parameter naming the underlying system's setting, and a value to set it to, etc. Along with an ``implementation()`` function that names the underlying technology, I'd be totally ok with this as the way to get at CherryPy's settings.

I think (2) is simpler, cleaner, and more powerful than (1). That is to say, I strongly prefer (2). Thoughts?

**Comment by manthey** [comment]
Yes, I think (2) is the correct approach.

**Comment by manthey** [comment]
As a practical use of this, currently when I want to change the pool size in cherrypy, I do `cherrypy.config.update({'server.thread_pool': 1000})` before running `tangelo.__main__.main()`.  This would be better served if it were in the config yaml file and processed as part of `main()`.  I imagine a new section in the config file, sort of like:
```
settings:
  -
    server:
      threadpool: 1000
```
and then an internal detail knows that settings[0]["server"]["threadpool"] maps to cherrypy in the appropriate way.

Internally, there could be new functions in util `get_setting(setting, defaultValue=None)` and `set_setting(setting, newValue)` (and perhaps `reset_setting(setting)` for completeness).  At the moment, I really only need `set_setting`, so the others could be left as a future PR.

**Comment by ronichoudhury** [comment]
This is pretty much exactly what I was thinking. Though, I don't know which
settings can be changed after startup, etc. I guess the get/set functions
could blindly do the underlying operation, and it's up to the user to know
what to expect.
