### ISSUE TITLE
Development dependencies aren't installed properly under NPM 3

### ISSUE THREAD

**Issue by manthey** [Kitware/tangelo#540]
With NPM 3, peer dependencies are no longer automatically installed.  grunt-blanket-qunit doesn't work because it fails to install grunt-contrib-qunit.  Adding it to the package.json doesn't seem to be sufficient, as grunt-blanket-qunit expects grunt-contrib-qunit to be in its own node_modules directory and not in the main node_modules directory.

**Comment by ronichoudhury** [comment]
Ok, I'll take a look.

**Comment by manthey** [comment]
I think, but haven't confirmed, that after `npm install`, if you `cd node_modules/grunt-blanket-qunit` and then do an `npm install` there, that it then works.  It may be necessary to do more.
