### ISSUE TITLE
Tangelo version 0.10.0 does not run changed code

### ISSUE THREAD

**Issue by sankhesh** [Kitware/tangelo#546]
If the underlying python code changes as a tangelo service is running, tangelo should run the updated codebase. This is broken as of version 0.10.0

Tested working with version 0.9.0

**Comment by manthey** [comment]
Are you using the `--watch` option or enabling the watch plugin in another manner?  In version 0.10.0, this became an option.

**Comment by sankhesh** [comment]
@manthey Thank you. That was it. 

@mathstuf FYI
